export const flexItemStyleValues = {
  alignSelf: [
    "auto",
    "flex-start",
    "flex-end",
    "center",
    "baseline",
    "stretch",
  ],
};

export const keyMapper = {
  justifyContent: "justify-content",
  alignContent: "align-content",
  alignItems: "align-items",
  flexWrap: "flex-wrap",
  columnGap: "column-gap",
  rowGap: "row-gap",
  flexDirection: "flex-direction",
};

/**
 * These are the default values defined by the CSS specification.
 */
export const flexContainerHTMLDefaultValues = {
  flexDirection: "row",
  flexWrap: "nowrap",
  justifyContent: "flex-start",
  alignItems: "stretch",
  alignContent: "normal",
  gap: "normal",
  rowGap: "normal",
  columnGap: "normal",
};

export const safeKeywords = ["safe", "unsafe"];

export const flexContainerStyleValues = {
  display: ["flex", "block", "inline-flex"],
  flexDirection: ["row", "row-reverse", "column", "column-reverse"],
  flexWrap: ["nowrap", "wrap", "column", "wrap-reverse"],
  justifyContent: [
    "flex-start",
    "flex-start safe",
    "flex-start unsafe",
    "flex-end",
    "flex-end safe",
    "flex-end unsafe",
    "center",
    "center safe",
    "center unsafe",
    "space-between",
    "space-between safe",
    "space-between unsafe",
    "space-around",
    "space-around safe",
    "space-around unsafe",
    "space-evenly",
    "space-evenly safe",
    "space-evenly unsafe",
    "start",
    "start safe",
    "start unsafe",
    "end",
    "end safe",
    "end unsafe",
    "left",
    "left safe",
    "left unsafe",
    "right",
    "right safe",
    "right unsafe",
  ],
  alignItems: [
    "stretch",
    "stretch safe",
    "stretch unsafe",
    "flex-start",
    "flex-start safe",
    "flex-start unsafe",
    "flex-end",
    "flex-end safe",
    "flex-end unsafe",
    "center",
    "center safe",
    "center unsafe",
    "baseline",
    "baseline safe",
    "baseline unsafe",
    "first baseline",
    "first baseline safe",
    "first baseline unsafe",
    "last baseline",
    "last baseline safe",
    "last baseline unsafe",
    "start",
    "start safe",
    "start unsafe",
    "end",
    "end safe",
    "end unsafe",
    "self-start",
    "self-start safe",
    "self-start unsafe",
    "self-end",
    "self-end safe",
    "self-end unsafe",
    "unset",
    "unset safe",
    "unset unsafe",
    "normal",
    "normal safe",
    "normal unsafe",
  ],
  alignContent: [
    "flex-start",
    "flex-start safe",
    "flex-start unsafe",
    "flex-end",
    "flex-end safe",
    "flex-end unsafe",
    "center",
    "center safe",
    "center unsafe",
    "space-between",
    "space-between safe",
    "space-between unsafe",
    "space-around",
    "space-around safe",
    "space-around unsafe",
    "space-evenly",
    "space-evenly safe",
    "space-evenly unsafe",
    "stretch",
    "stretch safe",
    "stretch unsafe",
    "start",
    "start safe",
    "start unsafe",
    "end",
    "end safe",
    "end unsafe",
    "baseline",
    "baseline safe",
    "baseline unsafe",
    "first baseline",
    "first baseline safe",
    "first baseline unsafe",
    "last baseline",
    "last baseline safe",
    "last baseline unsafe",
  ],
};
